//<auto-generated/>
#nullable enable
using System;
using System.IO;
using ProtoBuf;
using ProtoBuf.Meta;
using ProtobufNetTest;

namespace Devlooped
{
    /// <summary>
    /// Default implementation of <see cref="IBinaryDocumentSerializer"/> which 
    /// uses Newtonsoft.Json implementation of BSON for serialization.
    /// </summary>
    partial class ProtobufDocumentSerializer : IBinaryDocumentSerializer
    {
        /// <summary>
        /// Default instance of the serializer.
        /// </summary>
        public static IDocumentSerializer Default { get; } = new ProtobufDocumentSerializer();

        static ProtobufDocumentSerializer()
        {
            RuntimeTypeModel.Default.Add(typeof(DateTimeOffset), false).SetSurrogate(typeof(DateTimeOffsetSurrogate));
            RuntimeTypeModel.Default.Add(typeof(DateTimeOffset?), false).SetSurrogate(typeof(DateTimeOffsetSurrogate));
        }

        /// <inheritdoc />
        public T? Deserialize<T>(Stream stream)
        {
            if (stream.CanSeek && stream.Length == 0)
                return default;

            return (T?)Serializer.Deserialize(typeof(T), stream);
        }

        /// <inheritdoc />
        public void Serialize<T>(T value, Stream stream)
        {
            if (value == null)
                return;

            Serializer.Serialize(stream, value);
        }
    }
}
