//<auto-generated/>
#nullable enable
using System;
using System.Linq.Expressions;
using System.Reflection;

namespace Devlooped
{
    static class ExpressionExtensions
    {
        public static string? GetPropertyName<T, TResult>(this Expression<Func<T, TResult>>? expression)
        {
            if (expression == null)
                return null;

            if (expression.Body is MemberExpression member &&
                member.Member is PropertyInfo property)
                return property.Name;

            // We do not support anything except a straight property getter expression.
            return null;
        }
    }
}
