//<auto-generated/>
#nullable enable

using System.IO;

namespace Devlooped
{
    /// <summary>
    /// Serializes an object to/from a byte array.
    /// </summary>
    partial interface IBinaryDocumentSerializer : IDocumentSerializer
    {
        /// <summary>
        /// Serializes the value to a byte array.
        /// </summary>
        void Serialize<T>(T value, Stream stream);

        /// <summary>
        /// Deserializes an object from its serialized data.
        /// </summary>
        T? Deserialize<T>(Stream data);
    }
}
