//<auto-generated/>
#nullable enable
using Microsoft.Azure.Cosmos.Table;

namespace Devlooped
{
    /// <summary>
    /// Document metadata for <see cref="IDocumentRepository{T}"/> querying purposes.
    /// </summary>
    partial interface IDocumentEntity : ITableEntity
    {
        /// <summary>
        /// The type of the document, its <see cref="System.Type.FullName"/>.
        /// </summary>
        string? Type { get; }
        
        /// <summary>
        /// The major.minor version of the assembly the document type belongs to.
        /// </summary>
        string? Version { get; }
        
        /// <summary>
        /// The major component of the <see cref="Version"/>.
        /// </summary>
        int? MajorVersion { get; }

        /// <summary>
        /// The minor component of the <see cref="Version"/>.
        /// </summary>
        int? MinorVersion { get; }
    }
}
