//<auto-generated/>
#nullable enable

namespace Devlooped
{
    /// <summary>
    /// Serializes an object to/from a string.
    /// </summary>
    partial interface IStringDocumentSerializer : IDocumentSerializer
    {
        /// <summary>
        /// Serializes the value to a string.
        /// </summary>
        string Serialize<T>(T value);

        /// <summary>
        /// Deserializes an object from its serialized data.
        /// </summary>
        T? Deserialize<T>(string data);
    }
}
