//<auto-generated/>
#nullable enable
using System.Linq;

namespace Devlooped
{
    /// <summary>
    /// A specific partition within an <see cref="ITableRepository{T}"/>, which allows querying 
    /// by the entity properties, since they are stored in individual columns.
    /// </summary>
    /// <typeparam name="T">The type of entity being persisted.</typeparam>
    partial interface ITablePartition<T> : ITableStoragePartition<T> where T : class
    {
        /// <summary>
        /// Creates a query for use with LINQ expressions. See 
        /// <see ref="https://docs.microsoft.com/en-us/rest/api/storageservices/query-operators-supported-for-the-table-service">supported operators</see>.
        /// </summary>
        /// <remarks>
        /// The query is scoped to the current partition already.
        /// </remarks>
        /// <example>
        /// var books = TablePartition.Create&lt;Book&gt;("Bestsellers");
        /// await foreach (var book in books.CreateQuery().Where(x => x.IsPublished))
        /// {
        ///    Console.WriteLine(book.ISBN);
        /// }
        /// </example>
        /// <example>
        /// var books = TablePartition.Create&lt;Book&gt;("Bestsellers");
        /// await foreach (var published in from book in books.CreateQuery()
        ///                                 where book.IsPublished && book.Pages > 1000
        ///                                 select book)
        /// {
        ///    Console.WriteLine(published.ISBN);
        /// }
        /// </example>
        IQueryable<T> CreateQuery();
    }
}
