//<auto-generated/>
using System;
using System.Threading.Tasks;
using Azure.Data.Tables;

namespace Devlooped
{
    /// <summary>
    /// Represents a connection to a given <see cref="TableName"/> that 
    /// automatically creates the table if it doesn't exist.
    /// </summary>
    partial interface ITableConnection
    {
        /// <summary>
        /// Gets the name of the table in use.
        /// </summary>
        string TableName { get; }

        /// <summary>
        /// The table service endpoint for this connection.
        /// </summary>
        Uri Uri { get; }

        /// <summary>
        /// Gets table client for this connection, creating the table if it doesn't exist 
        /// on the first call to this method.
        /// </summary>
        Task<TableClient> GetTableAsync();
    }
}