//<auto-generated/>
#nullable enable
using System;
using System.ComponentModel;

namespace Devlooped
{
    /// <summary>
    /// Attribute that marks a method as non-mutating, meaning it doesn't change the value of 
    /// the received arguments if they are in turn returned to the caller.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [AttributeUsage(AttributeTargets.Method)]
    class NonMutatingAttribute : Attribute { }
}