//<auto-generated/>
using System;
using System.Threading.Tasks;
using Azure.Data.Tables;

namespace Devlooped
{
    class TableClientConnection : ITableConnection
    {
        readonly TableClient client;
        Task initialize;

        public TableClientConnection(TableClient client)
        {
            this.client = client;
            initialize = client.CreateIfNotExistsAsync();
        }

        public string TableName => client.Name;

        public Uri Uri => client.Uri;

        public async Task<TableClient> GetTableAsync()
        {
            await initialize;
            return client;
        }
    }
}
