//<auto-generated/>
#nullable enable
using Microsoft.Azure.Cosmos.Table;

namespace Devlooped
{
    /// <summary>
    /// Provides the strategy used when saving entities (using `PutAsync`) that 
    /// already exist in the table. Either <see cref="Merge"/> or <see cref="Replace"/>. 
    /// When not provided, <see cref="Replace"/> is used by default.
    /// </summary>
    abstract partial class UpdateStrategy
    {
        /// <summary>
        /// When storing an entity that already exists in the table, merge with the
        /// existing data, using <see cref="TableOperation.InsertOrMerge(ITableEntity)"/>.
        /// </summary>
        public static UpdateStrategy Merge { get; } = new MergeStrategy();

        /// <summary>
        /// When storing an entity that already exists in the table, replace the 
        /// existing data, using <see cref="TableOperation.InsertOrReplace(ITableEntity)"/>.
        /// </summary>
        public static UpdateStrategy Replace { get; } = new ReplaceStrategy();

        protected internal abstract TableOperation CreateOperation(ITableEntity entity);

        class MergeStrategy : UpdateStrategy
        {
            protected internal override TableOperation CreateOperation(ITableEntity entity)
                => TableOperation.InsertOrMerge(entity);
        }

        class ReplaceStrategy : UpdateStrategy
        {
            protected internal override TableOperation CreateOperation(ITableEntity entity)
                => TableOperation.InsertOrReplace(entity);
        }
    }
}
