//<auto-generated/>
#nullable enable
using MessagePack;

namespace Devlooped
{
    /// <summary>
    /// Default implementation of <see cref="IBinaryDocumentSerializer"/> which 
    /// uses Newtonsoft.Json implementation of BSON for serialization.
    /// </summary>
    partial class MessagePackDocumentSerializer : IBinaryDocumentSerializer
    {
        /// <summary>
        /// Default instance of the serializer.
        /// </summary>
        public static IDocumentSerializer Default { get; } = new MessagePackDocumentSerializer();

        /// <inheritdoc />
        public T? Deserialize<T>(byte[] data) => data.Length == 0 ? default : MessagePackSerializer.Deserialize<T>(data);

        /// <inheritdoc />
        public byte[] Serialize<T>(T value) => value == null ? new byte[0] : MessagePackSerializer.Serialize(value.GetType(), value);
    }
}
