//<auto-generated/>
#nullable enable
using System;
using System.Globalization;
using System.IO;
using Newtonsoft.Json;

namespace Devlooped
{
    /// <summary>
    /// Implementation of <see cref="IBinaryDocumentSerializer"/> which 
    /// uses Newtonsoft.Json implementation of BSON for serialization.
    /// </summary>
    partial class BsonDocumentSerializer : IBinaryDocumentSerializer
    {
        static readonly JsonSerializer serializer =
#if NET6_0_OR_GREATER
            JsonSerializer.Create(new JsonSerializerSettings
            {
                Converters =
                {
                    new DateOnlyJsonConverter(),
                }
            });
#else
            new JsonSerializer();
#endif

        /// <summary>
        /// Default instance of the serializer.
        /// </summary>
        public static IDocumentSerializer Default { get; } = new BsonDocumentSerializer();

        /// <inheritdoc />
        public T? Deserialize<T>(byte[] data)
        {
            if (data.Length == 0)
                return default;

            using var mem = new MemoryStream(data);
            using var reader = new Newtonsoft.Json.Bson.BsonDataReader(mem);
            return (T?)serializer.Deserialize<T>(reader);
        }

        /// <inheritdoc />
        public byte[] Serialize<T>(T value)
        {
            if (value == null)
                return new byte[0];

            using var mem = new MemoryStream();
            using var writer = new Newtonsoft.Json.Bson.BsonDataWriter(mem);
            serializer.Serialize(writer, value);
            return mem.ToArray();
        }

#if NET6_0_OR_GREATER
        class DateOnlyJsonConverter : JsonConverter<DateOnly>
        {
            public override DateOnly ReadJson(JsonReader reader, Type objectType, DateOnly existingValue, bool hasExistingValue, JsonSerializer serializer)
                => DateOnly.Parse((string)reader.Value!, CultureInfo.InvariantCulture);

            public override void WriteJson(JsonWriter writer, DateOnly value, JsonSerializer serializer)
                => writer.WriteValue(value.ToString("O", CultureInfo.InvariantCulture));
        }
#endif
    }
}
